name: Add Footer to Markdown Files

on:
  push:
    paths:
      - '**/*.md'  # Trigger on changes to all markdown files

jobs:
  insert-footer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add footer to Markdown files
        run: |
          # Path to footer.md
          FOOTER_PATH=docs/includes/_footer.md

          # Append footer content to all markdown files
          for file in $(find . -name "*.md"); do
            cat $FOOTER_PATH >> $file
          done

      - name: Commit changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'youremail@example.com'
          git add .
          git commit -m "Added footer to all markdown files"
          git push
